version: '3.8'
services:
  app:
    container_name: LibraryAPI
    build: .
    ports: 
      - 8000:8000 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db
      - cache          
    networks:
      - netapi


  db:
    image: postgres:latest
    container_name: LibraryAPI_DB
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - netapi
  
  cache:
    image: redis:6.2-alpine
    container_name: LibraryAPI_Cache
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    command: > 
      --requirepass ${REDIS_PASS}
    ports:
      - '6379:6379'
    networks:
      - netapi
    

volumes:
  api:
  postgres_data:                  

# Networks to be created to facilitate communication between containers
networks:
  netapi:
    driver: bridge