version: '3.8'
services:
  app:
    container_name: LibraryAPI
    build: .
    ports: 
      - 8000:8000 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db          
    networks:
      - netapi


  db:
    image: postgres:latest
    container_name: LibraryAPI_DB
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - netapi
    

volumes:
  api:
  postgres_data:                  

# Networks to be created to facilitate communication between containers
networks:
  netapi:
    driver: bridge